---
server:
  context-path: /
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
  datasource:
    driverClassName: org.postgresql.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: REMOVED
    username: REMOVED
    password: REMOVED
    tomcat:
      max-active: 100
      max-idle: 6
      min-idle: 1
      initial-size: 50
      name: spring/datasource

resteasy:
  deployment:
    async_job_service_enabled: true


management:
  context-path: /actuator
  security:
    enabled: true
    roles: MANAGER

keycloak:
  server:
    contextPath: /auth

security:
  user:
    name: manager
    password: manager
    role: MANAGER

  basic:
    enabled: true
    path: /mgmt
